name: deploy
on:
  push:
    branches: [ bash ]
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
# 设置上海时区
env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout dev
        run: |
          wget https://github.com/Tencent/tdesign-vue-starter/archive/refs/tags/v0.1.0.tar.gz
          tar xf tdesign-vue-starter-0.1.0.tar.gz
          mv tdesign-vue-starter-0.1.0 vue
          wget https://github.com/Tencent/tdesign-vue-next-starter/archive/refs/tags/0.1.0.tar.gz
          tar xf tdesign-vue-next-starter-0.1.0.tar.gz
          mv tdesign-vue-next-starter-0.1.0 vue-next
      - name: Deploy vue 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: vue
          FOLDER: vue
      - name: Deploy master 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: vue
      - name: Deploy vue-next 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: vue-next
          FOLDER: vue-next
      - name: Deploy main 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main
          FOLDER: vue-next

  clean:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚀
        uses: actions/checkout@v2
        with:
          repository: 'jdsync/Workflows-Cleaner'
      - name: Set up Python 🚀
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install pipenv 🚀
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXPIRE_TIME: '1h'
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv install
          pipenv run python run.py
